package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.ListeningQuestionsInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface ListeningQuestionsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listeningQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int insert(ListeningQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int insertSelective(ListeningQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    ListeningQuestionsInfo selectByPrimaryKey(Integer listeningQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ListeningQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ListeningQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ListeningQuestionsInfo row);
}