package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.ListeningChoicesInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface ListeningChoicesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer listenChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    int insert(ListeningChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    int insertSelective(ListeningChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    ListeningChoicesInfo selectByPrimaryKey(Integer listenChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ListeningChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_choices_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ListeningChoicesInfo row);
}