package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.ReadingChoicesInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface ReadingChoicesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer readChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    int insert(ReadingChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    int insertSelective(ReadingChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    ReadingChoicesInfo selectByPrimaryKey(Integer readChoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReadingChoicesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_choices_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReadingChoicesInfo row);
}