package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.ReadingQuestionsInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface ReadingQuestionsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer readingQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int insert(ReadingQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int insertSelective(ReadingQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    ReadingQuestionsInfo selectByPrimaryKey(Integer readingQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReadingQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ReadingQuestionsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading_questions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReadingQuestionsInfo row);
}