package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.WordSynonymsInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface WordSynonymsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wordSynonymId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    int insert(WordSynonymsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    int insertSelective(WordSynonymsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    WordSynonymsInfo selectByPrimaryKey(Integer wordSynonymId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WordSynonymsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_synonyms_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WordSynonymsInfo row);
}