package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.WordPhrasesInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface WordPhrasesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wordPhraseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    int insert(WordPhrasesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    int insertSelective(WordPhrasesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    WordPhrasesInfo selectByPrimaryKey(Integer wordPhraseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WordPhrasesInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_phrases_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WordPhrasesInfo row);
}