package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.WordsRootInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface WordsRootInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wordRootId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    int insert(WordsRootInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    int insertSelective(WordsRootInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    WordsRootInfo selectByPrimaryKey(Integer wordRootId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WordsRootInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table words_root_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WordsRootInfo row);
}