package com.eLearnPlayer.mapper;

import com.eLearnPlayer.entity.WordToCollectionInfoKey;
import org.springframework.stereotype.Repository;

@Repository
public interface WordToCollectionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_to_collection_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(WordToCollectionInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_to_collection_info
     *
     * @mbg.generated
     */
    int insert(WordToCollectionInfoKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_to_collection_info
     *
     * @mbg.generated
     */
    int insertSelective(WordToCollectionInfoKey row);
}