package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table level_info
 */
@Table(name = "level_info")
public class LevelInfo {
    /**
     * Database Column Remarks:
     *   ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_info.Level
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer level;

    /**
     * Database Column Remarks:
     *   ˮƽ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_info.Grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_info.Level
     *
     * @return the value of level_info.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_info.Level
     *
     * @param level the value for level_info.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_info.Grade
     *
     * @return the value of level_info.Grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_info.Grade
     *
     * @param grade the value for level_info.Grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}