package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table listening_choices_info
 */
@Table(name = "listening_choices_info")
public class ListeningChoicesInfo {
    /**
     * Database Column Remarks:
     *   选项id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_choices_info.Listen_Choice_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer listenChoiceId;

    /**
     * Database Column Remarks:
     *    外键，问题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_choices_info.Listening_Question_id
     *
     * @mbg.generated
     */
    private Integer listeningQuestionId;

    /**
     * Database Column Remarks:
     *    选项索引
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_choices_info.Choice_index
     *
     * @mbg.generated
     */
    private Integer choiceIndex;

    /**
     * Database Column Remarks:
     *    选项内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_choices_info.Choice_text
     *
     * @mbg.generated
     */
    private String choiceText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_choices_info.Listen_Choice_id
     *
     * @return the value of listening_choices_info.Listen_Choice_id
     *
     * @mbg.generated
     */
    public Integer getListenChoiceId() {
        return listenChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_choices_info.Listen_Choice_id
     *
     * @param listenChoiceId the value for listening_choices_info.Listen_Choice_id
     *
     * @mbg.generated
     */
    public void setListenChoiceId(Integer listenChoiceId) {
        this.listenChoiceId = listenChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_choices_info.Listening_Question_id
     *
     * @return the value of listening_choices_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public Integer getListeningQuestionId() {
        return listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_choices_info.Listening_Question_id
     *
     * @param listeningQuestionId the value for listening_choices_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public void setListeningQuestionId(Integer listeningQuestionId) {
        this.listeningQuestionId = listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_choices_info.Choice_index
     *
     * @return the value of listening_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public Integer getChoiceIndex() {
        return choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_choices_info.Choice_index
     *
     * @param choiceIndex the value for listening_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public void setChoiceIndex(Integer choiceIndex) {
        this.choiceIndex = choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_choices_info.Choice_text
     *
     * @return the value of listening_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public String getChoiceText() {
        return choiceText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_choices_info.Choice_text
     *
     * @param choiceText the value for listening_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public void setChoiceText(String choiceText) {
        this.choiceText = choiceText == null ? null : choiceText.trim();
    }
}