package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table listening_questions_info
 */
@Table(name = "listening_questions_info")
public class ListeningQuestionsInfo {
    /**
     * Database Column Remarks:
     *   题目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_questions_info.Listening_Question_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer listeningQuestionId;

    /**
     * Database Column Remarks:
     *   音频id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_questions_info.Audio_id
     *
     * @mbg.generated
     */
    private Integer audioId;

    /**
     * Database Column Remarks:
     *    正确答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_questions_info.Correct_answer
     *
     * @mbg.generated
     */
    private String correctAnswer;

    /**
     * Database Column Remarks:
     *    题目内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_questions_info. Passage_text
     *
     * @mbg.generated
     */
    private String passageText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_questions_info.Listening_Question_id
     *
     * @return the value of listening_questions_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public Integer getListeningQuestionId() {
        return listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_questions_info.Listening_Question_id
     *
     * @param listeningQuestionId the value for listening_questions_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public void setListeningQuestionId(Integer listeningQuestionId) {
        this.listeningQuestionId = listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_questions_info.Audio_id
     *
     * @return the value of listening_questions_info.Audio_id
     *
     * @mbg.generated
     */
    public Integer getAudioId() {
        return audioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_questions_info.Audio_id
     *
     * @param audioId the value for listening_questions_info.Audio_id
     *
     * @mbg.generated
     */
    public void setAudioId(Integer audioId) {
        this.audioId = audioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_questions_info.Correct_answer
     *
     * @return the value of listening_questions_info.Correct_answer
     *
     * @mbg.generated
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_questions_info.Correct_answer
     *
     * @param correctAnswer the value for listening_questions_info.Correct_answer
     *
     * @mbg.generated
     */
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer == null ? null : correctAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_questions_info. Passage_text
     *
     * @return the value of listening_questions_info. Passage_text
     *
     * @mbg.generated
     */
    public String getPassageText() {
        return passageText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_questions_info. Passage_text
     *
     * @param passageText the value for listening_questions_info. Passage_text
     *
     * @mbg.generated
     */
    public void setPassageText(String passageText) {
        this.passageText = passageText == null ? null : passageText.trim();
    }
}