package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table listening_audio_info
 */
@Table(name = "listening_audio_info")
public class ListeningAudioInfo {
    /**
     * Database Column Remarks:
     *   音频id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_audio_info.Audio_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer audioId;

    /**
     * Database Column Remarks:
     *   音频标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_audio_info.Audio_title
     *
     * @mbg.generated
     */
    private String audioTitle;

    /**
     * Database Column Remarks:
     *   音频文件路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_audio_info.Audio_file
     *
     * @mbg.generated
     */
    private String audioFile;

    /**
     * Database Column Remarks:
     *   级别，外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listening_audio_info.Level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_audio_info.Audio_id
     *
     * @return the value of listening_audio_info.Audio_id
     *
     * @mbg.generated
     */
    public Integer getAudioId() {
        return audioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_audio_info.Audio_id
     *
     * @param audioId the value for listening_audio_info.Audio_id
     *
     * @mbg.generated
     */
    public void setAudioId(Integer audioId) {
        this.audioId = audioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_audio_info.Audio_title
     *
     * @return the value of listening_audio_info.Audio_title
     *
     * @mbg.generated
     */
    public String getAudioTitle() {
        return audioTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_audio_info.Audio_title
     *
     * @param audioTitle the value for listening_audio_info.Audio_title
     *
     * @mbg.generated
     */
    public void setAudioTitle(String audioTitle) {
        this.audioTitle = audioTitle == null ? null : audioTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_audio_info.Audio_file
     *
     * @return the value of listening_audio_info.Audio_file
     *
     * @mbg.generated
     */
    public String getAudioFile() {
        return audioFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_audio_info.Audio_file
     *
     * @param audioFile the value for listening_audio_info.Audio_file
     *
     * @mbg.generated
     */
    public void setAudioFile(String audioFile) {
        this.audioFile = audioFile == null ? null : audioFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listening_audio_info.Level
     *
     * @return the value of listening_audio_info.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listening_audio_info.Level
     *
     * @param level the value for listening_audio_info.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}