package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table medal_info
 */
@Table(name = "medal_info")
public class MedalInfo {
    /**
     * Database Column Remarks:
     *   ѫ��id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medal_info.Medal_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer medalId;

    /**
     * Database Column Remarks:
     *   ѫ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medal_info.Medal_name
     *
     * @mbg.generated
     */
    private String medalName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medal_info.Medal_id
     *
     * @return the value of medal_info.Medal_id
     *
     * @mbg.generated
     */
    public Integer getMedalId() {
        return medalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medal_info.Medal_id
     *
     * @param medalId the value for medal_info.Medal_id
     *
     * @mbg.generated
     */
    public void setMedalId(Integer medalId) {
        this.medalId = medalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medal_info.Medal_name
     *
     * @return the value of medal_info.Medal_name
     *
     * @mbg.generated
     */
    public String getMedalName() {
        return medalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medal_info.Medal_name
     *
     * @param medalName the value for medal_info.Medal_name
     *
     * @mbg.generated
     */
    public void setMedalName(String medalName) {
        this.medalName = medalName == null ? null : medalName.trim();
    }
}