package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reading_questions_info
 */
@Table(name = "reading_questions_info")
public class ReadingQuestionsInfo {
    /**
     * Database Column Remarks:
     *   ��Ŀid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_questions_info.Reading_Question_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer readingQuestionId;

    /**
     * Database Column Remarks:
     *    ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_questions_info.Passage_id
     *
     * @mbg.generated
     */
    private Integer passageId;

    /**
     * Database Column Remarks:
     *    ��ȷ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_questions_info.correct_answer
     *
     * @mbg.generated
     */
    private String correctAnswer;

    /**
     * Database Column Remarks:
     *    ��Ŀ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_questions_info.Passage_text
     *
     * @mbg.generated
     */
    private String passageText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_questions_info.Reading_Question_id
     *
     * @return the value of reading_questions_info.Reading_Question_id
     *
     * @mbg.generated
     */
    public Integer getReadingQuestionId() {
        return readingQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_questions_info.Reading_Question_id
     *
     * @param readingQuestionId the value for reading_questions_info.Reading_Question_id
     *
     * @mbg.generated
     */
    public void setReadingQuestionId(Integer readingQuestionId) {
        this.readingQuestionId = readingQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_questions_info.Passage_id
     *
     * @return the value of reading_questions_info.Passage_id
     *
     * @mbg.generated
     */
    public Integer getPassageId() {
        return passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_questions_info.Passage_id
     *
     * @param passageId the value for reading_questions_info.Passage_id
     *
     * @mbg.generated
     */
    public void setPassageId(Integer passageId) {
        this.passageId = passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_questions_info.correct_answer
     *
     * @return the value of reading_questions_info.correct_answer
     *
     * @mbg.generated
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_questions_info.correct_answer
     *
     * @param correctAnswer the value for reading_questions_info.correct_answer
     *
     * @mbg.generated
     */
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer == null ? null : correctAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_questions_info.Passage_text
     *
     * @return the value of reading_questions_info.Passage_text
     *
     * @mbg.generated
     */
    public String getPassageText() {
        return passageText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_questions_info.Passage_text
     *
     * @param passageText the value for reading_questions_info.Passage_text
     *
     * @mbg.generated
     */
    public void setPassageText(String passageText) {
        this.passageText = passageText == null ? null : passageText.trim();
    }
}