package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reading_passages_info
 */
@Table(name = "reading_passages_info")
public class ReadingPassagesInfo {
    /**
     * Database Column Remarks:
     *   ����id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_passages_info.Passage_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer passageId;

    /**
     * Database Column Remarks:
     *    ���±���
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_passages_info.Passage_title
     *
     * @mbg.generated
     */
    private String passageTitle;

    /**
     * Database Column Remarks:
     *    ���������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_passages_info.Level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     * Database Column Remarks:
     *    ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_passages_info.Passage_text
     *
     * @mbg.generated
     */
    private String passageText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_passages_info.Passage_id
     *
     * @return the value of reading_passages_info.Passage_id
     *
     * @mbg.generated
     */
    public Integer getPassageId() {
        return passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_passages_info.Passage_id
     *
     * @param passageId the value for reading_passages_info.Passage_id
     *
     * @mbg.generated
     */
    public void setPassageId(Integer passageId) {
        this.passageId = passageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_passages_info.Passage_title
     *
     * @return the value of reading_passages_info.Passage_title
     *
     * @mbg.generated
     */
    public String getPassageTitle() {
        return passageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_passages_info.Passage_title
     *
     * @param passageTitle the value for reading_passages_info.Passage_title
     *
     * @mbg.generated
     */
    public void setPassageTitle(String passageTitle) {
        this.passageTitle = passageTitle == null ? null : passageTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_passages_info.Level
     *
     * @return the value of reading_passages_info.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_passages_info.Level
     *
     * @param level the value for reading_passages_info.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_passages_info.Passage_text
     *
     * @return the value of reading_passages_info.Passage_text
     *
     * @mbg.generated
     */
    public String getPassageText() {
        return passageText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_passages_info.Passage_text
     *
     * @param passageText the value for reading_passages_info.Passage_text
     *
     * @mbg.generated
     */
    public void setPassageText(String passageText) {
        this.passageText = passageText == null ? null : passageText.trim();
    }
}