package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reading_choices_info
 */
@Table(name = "reading_choices_info")
public class ReadingChoicesInfo {
    /**
     * Database Column Remarks:
     *   ѡ��id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_choices_info.Read_Choice_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer readChoiceId;

    /**
     * Database Column Remarks:
     *    ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_choices_info.Reading_Question_id
     *
     * @mbg.generated
     */
    private Integer readingQuestionId;

    /**
     * Database Column Remarks:
     *    ѡ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_choices_info.Choice_index
     *
     * @mbg.generated
     */
    private Integer choiceIndex;

    /**
     * Database Column Remarks:
     *    ѡ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reading_choices_info.Choice_text
     *
     * @mbg.generated
     */
    private String choiceText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_choices_info.Read_Choice_id
     *
     * @return the value of reading_choices_info.Read_Choice_id
     *
     * @mbg.generated
     */
    public Integer getReadChoiceId() {
        return readChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_choices_info.Read_Choice_id
     *
     * @param readChoiceId the value for reading_choices_info.Read_Choice_id
     *
     * @mbg.generated
     */
    public void setReadChoiceId(Integer readChoiceId) {
        this.readChoiceId = readChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_choices_info.Reading_Question_id
     *
     * @return the value of reading_choices_info.Reading_Question_id
     *
     * @mbg.generated
     */
    public Integer getReadingQuestionId() {
        return readingQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_choices_info.Reading_Question_id
     *
     * @param readingQuestionId the value for reading_choices_info.Reading_Question_id
     *
     * @mbg.generated
     */
    public void setReadingQuestionId(Integer readingQuestionId) {
        this.readingQuestionId = readingQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_choices_info.Choice_index
     *
     * @return the value of reading_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public Integer getChoiceIndex() {
        return choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_choices_info.Choice_index
     *
     * @param choiceIndex the value for reading_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public void setChoiceIndex(Integer choiceIndex) {
        this.choiceIndex = choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reading_choices_info.Choice_text
     *
     * @return the value of reading_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public String getChoiceText() {
        return choiceText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reading_choices_info.Choice_text
     *
     * @param choiceText the value for reading_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public void setChoiceText(String choiceText) {
        this.choiceText = choiceText == null ? null : choiceText.trim();
    }
}