package com.eLearnPlayer.entity;

import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sentence_info
 */
@Table(name = "sentence_info")
public class SentenceInfoWithBLOBs extends SentenceInfo {
    /**
     * Database Column Remarks:
     *    英语例句
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_info.English_content
     *
     * @mbg.generated
     */
    private String englishContent;

    /**
     * Database Column Remarks:
     *    中文翻译
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_info.Chinese_content
     *
     * @mbg.generated
     */
    private String chineseContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_info.English_content
     *
     * @return the value of sentence_info.English_content
     *
     * @mbg.generated
     */
    public String getEnglishContent() {
        return englishContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_info.English_content
     *
     * @param englishContent the value for sentence_info.English_content
     *
     * @mbg.generated
     */
    public void setEnglishContent(String englishContent) {
        this.englishContent = englishContent == null ? null : englishContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_info.Chinese_content
     *
     * @return the value of sentence_info.Chinese_content
     *
     * @mbg.generated
     */
    public String getChineseContent() {
        return chineseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_info.Chinese_content
     *
     * @param chineseContent the value for sentence_info.Chinese_content
     *
     * @mbg.generated
     */
    public void setChineseContent(String chineseContent) {
        this.chineseContent = chineseContent == null ? null : chineseContent.trim();
    }
}