package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sentence_info
 */
@Table(name = "sentence_info")
public class SentenceInfo {
    /**
     * Database Column Remarks:
     *   例句id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_info.Sentence_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer sentenceId;

    /**
     * Database Column Remarks:
     *    外键，单词id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sentence_info.Word_id
     *
     * @mbg.generated
     */
    private Integer wordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_info.Sentence_id
     *
     * @return the value of sentence_info.Sentence_id
     *
     * @mbg.generated
     */
    public Integer getSentenceId() {
        return sentenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_info.Sentence_id
     *
     * @param sentenceId the value for sentence_info.Sentence_id
     *
     * @mbg.generated
     */
    public void setSentenceId(Integer sentenceId) {
        this.sentenceId = sentenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sentence_info.Word_id
     *
     * @return the value of sentence_info.Word_id
     *
     * @mbg.generated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sentence_info.Word_id
     *
     * @param wordId the value for sentence_info.Word_id
     *
     * @mbg.generated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }
}