package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_info
 */
@Table(name = "user_info")
public class UserInfo {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.User_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer userId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.User_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *    密码（md5加密）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.User_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     * Database Column Remarks:
     *    昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *    性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *    联系方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *    头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Head
     *
     * @mbg.generated
     */
    private String head;

    /**
     * Database Column Remarks:
     *    金币
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Gold
     *
     * @mbg.generated
     */
    private Integer gold;

    /**
     * Database Column Remarks:
     *    钻石
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Jewel
     *
     * @mbg.generated
     */
    private Integer jewel;

    /**
     * Database Column Remarks:
     *    外键，级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     * Database Column Remarks:
     *    闯关等级（1-1，3-4）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Rank
     *
     * @mbg.generated
     */
    private String rank;

    /**
     * Database Column Remarks:
     *   外键，勋章id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.Medal_id
     *
     * @mbg.generated
     */
    private Integer medalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.User_id
     *
     * @return the value of user_info.User_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.User_id
     *
     * @param userId the value for user_info.User_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.User_name
     *
     * @return the value of user_info.User_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.User_name
     *
     * @param userName the value for user_info.User_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.User_password
     *
     * @return the value of user_info.User_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.User_password
     *
     * @param userPassword the value for user_info.User_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Nick_name
     *
     * @return the value of user_info.Nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Nick_name
     *
     * @param nickName the value for user_info.Nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Sex
     *
     * @return the value of user_info.Sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Sex
     *
     * @param sex the value for user_info.Sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Phone
     *
     * @return the value of user_info.Phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Phone
     *
     * @param phone the value for user_info.Phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Head
     *
     * @return the value of user_info.Head
     *
     * @mbg.generated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Head
     *
     * @param head the value for user_info.Head
     *
     * @mbg.generated
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Gold
     *
     * @return the value of user_info.Gold
     *
     * @mbg.generated
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Gold
     *
     * @param gold the value for user_info.Gold
     *
     * @mbg.generated
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Jewel
     *
     * @return the value of user_info.Jewel
     *
     * @mbg.generated
     */
    public Integer getJewel() {
        return jewel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Jewel
     *
     * @param jewel the value for user_info.Jewel
     *
     * @mbg.generated
     */
    public void setJewel(Integer jewel) {
        this.jewel = jewel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Level
     *
     * @return the value of user_info.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Level
     *
     * @param level the value for user_info.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Rank
     *
     * @return the value of user_info.Rank
     *
     * @mbg.generated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Rank
     *
     * @param rank the value for user_info.Rank
     *
     * @mbg.generated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.Medal_id
     *
     * @return the value of user_info.Medal_id
     *
     * @mbg.generated
     */
    public Integer getMedalId() {
        return medalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.Medal_id
     *
     * @param medalId the value for user_info.Medal_id
     *
     * @mbg.generated
     */
    public void setMedalId(Integer medalId) {
        this.medalId = medalId;
    }
}