package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_listening_answers_info
 */
@Table(name = "user_listening_answers_info")
public class UserListeningAnswersInfo {
    /**
     * Database Column Remarks:
     *   ��¼id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_listening_answers_info.User_Listening_answer_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer userListeningAnswerId;

    /**
     * Database Column Remarks:
     *    �û�id�����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_listening_answers_info.User_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *    ��Ŀid�����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_listening_answers_info.Listening_Question_id
     *
     * @mbg.generated
     */
    private Integer listeningQuestionId;

    /**
     * Database Column Remarks:
     *    �û�ѡ��Ĵ�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_listening_answers_info.Selected_answer
     *
     * @mbg.generated
     */
    private String selectedAnswer;

    /**
     * Database Column Remarks:
     *   �Ƿ���ȷ��1�ԣ�0��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_listening_answers_info.Is_correct
     *
     * @mbg.generated
     */
    private Boolean isCorrect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_listening_answers_info.User_Listening_answer_id
     *
     * @return the value of user_listening_answers_info.User_Listening_answer_id
     *
     * @mbg.generated
     */
    public Integer getUserListeningAnswerId() {
        return userListeningAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_listening_answers_info.User_Listening_answer_id
     *
     * @param userListeningAnswerId the value for user_listening_answers_info.User_Listening_answer_id
     *
     * @mbg.generated
     */
    public void setUserListeningAnswerId(Integer userListeningAnswerId) {
        this.userListeningAnswerId = userListeningAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_listening_answers_info.User_id
     *
     * @return the value of user_listening_answers_info.User_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_listening_answers_info.User_id
     *
     * @param userId the value for user_listening_answers_info.User_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_listening_answers_info.Listening_Question_id
     *
     * @return the value of user_listening_answers_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public Integer getListeningQuestionId() {
        return listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_listening_answers_info.Listening_Question_id
     *
     * @param listeningQuestionId the value for user_listening_answers_info.Listening_Question_id
     *
     * @mbg.generated
     */
    public void setListeningQuestionId(Integer listeningQuestionId) {
        this.listeningQuestionId = listeningQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_listening_answers_info.Selected_answer
     *
     * @return the value of user_listening_answers_info.Selected_answer
     *
     * @mbg.generated
     */
    public String getSelectedAnswer() {
        return selectedAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_listening_answers_info.Selected_answer
     *
     * @param selectedAnswer the value for user_listening_answers_info.Selected_answer
     *
     * @mbg.generated
     */
    public void setSelectedAnswer(String selectedAnswer) {
        this.selectedAnswer = selectedAnswer == null ? null : selectedAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_listening_answers_info.Is_correct
     *
     * @return the value of user_listening_answers_info.Is_correct
     *
     * @mbg.generated
     */
    public Boolean getIsCorrect() {
        return isCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_listening_answers_info.Is_correct
     *
     * @param isCorrect the value for user_listening_answers_info.Is_correct
     *
     * @mbg.generated
     */
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }
}