package com.eLearnPlayer.entity;


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_collections_info
 */
@Table(name = "word_collections_info")
public class WordCollectionsInfo {
    /**
     * Database Column Remarks:
     *   收藏夹id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collections_info.Word_Collection_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer wordCollectionId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collections_info.User_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   收藏夹名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collections_info.Collection_name
     *
     * @mbg.generated
     */
    private String collectionName;

    /**
     * Database Column Remarks:
     *   收藏夹描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collections_info.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collections_info.Word_Collection_id
     *
     * @return the value of word_collections_info.Word_Collection_id
     *
     * @mbg.generated
     */
    public Integer getWordCollectionId() {
        return wordCollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collections_info.Word_Collection_id
     *
     * @param wordCollectionId the value for word_collections_info.Word_Collection_id
     *
     * @mbg.generated
     */
    public void setWordCollectionId(Integer wordCollectionId) {
        this.wordCollectionId = wordCollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collections_info.User_id
     *
     * @return the value of word_collections_info.User_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collections_info.User_id
     *
     * @param userId the value for word_collections_info.User_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collections_info.Collection_name
     *
     * @return the value of word_collections_info.Collection_name
     *
     * @mbg.generated
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collections_info.Collection_name
     *
     * @param collectionName the value for word_collections_info.Collection_name
     *
     * @mbg.generated
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName == null ? null : collectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collections_info.Description
     *
     * @return the value of word_collections_info.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collections_info.Description
     *
     * @param description the value for word_collections_info.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}