package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_phrases_info
 */
@Table(name = "word_phrases_info")
public class WordPhrasesInfo {
    /**
     * Database Column Remarks:
     *   ����id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_phrases_info.Word_Phrase_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer wordPhraseId;

    /**
     * Database Column Remarks:
     *   ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_phrases_info.Word_id
     *
     * @mbg.generated
     */
    private Integer wordId;

    /**
     * Database Column Remarks:
     *    ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_phrases_info.Phrase_content
     *
     * @mbg.generated
     */
    private String phraseContent;

    /**
     * Database Column Remarks:
     *    ���﷭��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_phrases_info.Phrase_translation
     *
     * @mbg.generated
     */
    private String phraseTranslation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_phrases_info.Word_Phrase_id
     *
     * @return the value of word_phrases_info.Word_Phrase_id
     *
     * @mbg.generated
     */
    public Integer getWordPhraseId() {
        return wordPhraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_phrases_info.Word_Phrase_id
     *
     * @param wordPhraseId the value for word_phrases_info.Word_Phrase_id
     *
     * @mbg.generated
     */
    public void setWordPhraseId(Integer wordPhraseId) {
        this.wordPhraseId = wordPhraseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_phrases_info.Word_id
     *
     * @return the value of word_phrases_info.Word_id
     *
     * @mbg.generated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_phrases_info.Word_id
     *
     * @param wordId the value for word_phrases_info.Word_id
     *
     * @mbg.generated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_phrases_info.Phrase_content
     *
     * @return the value of word_phrases_info.Phrase_content
     *
     * @mbg.generated
     */
    public String getPhraseContent() {
        return phraseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_phrases_info.Phrase_content
     *
     * @param phraseContent the value for word_phrases_info.Phrase_content
     *
     * @mbg.generated
     */
    public void setPhraseContent(String phraseContent) {
        this.phraseContent = phraseContent == null ? null : phraseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_phrases_info.Phrase_translation
     *
     * @return the value of word_phrases_info.Phrase_translation
     *
     * @mbg.generated
     */
    public String getPhraseTranslation() {
        return phraseTranslation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_phrases_info.Phrase_translation
     *
     * @param phraseTranslation the value for word_phrases_info.Phrase_translation
     *
     * @mbg.generated
     */
    public void setPhraseTranslation(String phraseTranslation) {
        this.phraseTranslation = phraseTranslation == null ? null : phraseTranslation.trim();
    }
}