package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table words_root_info
 */
@Table(name = "words_root_info")
public class WordsRootInfo {
    /**
     * Database Column Remarks:
     *   ͬ����id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words_root_info.Word_Root_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer wordRootId;

    /**
     * Database Column Remarks:
     *    ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words_root_info.Word_id
     *
     * @mbg.generated
     */
    private Integer wordId;

    /**
     * Database Column Remarks:
     *    ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words_root_info.Part_of_speech
     *
     * @mbg.generated
     */
    private String partOfSpeech;

    /**
     * Database Column Remarks:
     *    ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words_root_info.Root_translation
     *
     * @mbg.generated
     */
    private String rootTranslation;

    /**
     * Database Column Remarks:
     *   ͬ����
     *   ͬ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column words_root_info.Root_word
     *
     * @mbg.generated
     */
    private String rootWord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words_root_info.Word_Root_id
     *
     * @return the value of words_root_info.Word_Root_id
     *
     * @mbg.generated
     */
    public Integer getWordRootId() {
        return wordRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words_root_info.Word_Root_id
     *
     * @param wordRootId the value for words_root_info.Word_Root_id
     *
     * @mbg.generated
     */
    public void setWordRootId(Integer wordRootId) {
        this.wordRootId = wordRootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words_root_info.Word_id
     *
     * @return the value of words_root_info.Word_id
     *
     * @mbg.generated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words_root_info.Word_id
     *
     * @param wordId the value for words_root_info.Word_id
     *
     * @mbg.generated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words_root_info.Part_of_speech
     *
     * @return the value of words_root_info.Part_of_speech
     *
     * @mbg.generated
     */
    public String getPartOfSpeech() {
        return partOfSpeech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words_root_info.Part_of_speech
     *
     * @param partOfSpeech the value for words_root_info.Part_of_speech
     *
     * @mbg.generated
     */
    public void setPartOfSpeech(String partOfSpeech) {
        this.partOfSpeech = partOfSpeech == null ? null : partOfSpeech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words_root_info.Root_translation
     *
     * @return the value of words_root_info.Root_translation
     *
     * @mbg.generated
     */
    public String getRootTranslation() {
        return rootTranslation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words_root_info.Root_translation
     *
     * @param rootTranslation the value for words_root_info.Root_translation
     *
     * @mbg.generated
     */
    public void setRootTranslation(String rootTranslation) {
        this.rootTranslation = rootTranslation == null ? null : rootTranslation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column words_root_info.Root_word
     *
     * @return the value of words_root_info.Root_word
     *
     * @mbg.generated
     */
    public String getRootWord() {
        return rootWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column words_root_info.Root_word
     *
     * @param rootWord the value for words_root_info.Root_word
     *
     * @mbg.generated
     */
    public void setRootWord(String rootWord) {
        this.rootWord = rootWord == null ? null : rootWord.trim();
    }
}