package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_question_info
 */
@Table(name = "word_question_info")
public class WordQuestionInfo {
    /**
     * Database Column Remarks:
     *   ��������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_question_info.Word_Question_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer wordQuestionId;

    /**
     * Database Column Remarks:
     *    ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_question_info.Word_id
     *
     * @mbg.generated
     */
    private Integer wordId;

    /**
     * Database Column Remarks:
     *    ��ȷѡ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_question_info.Correct_choice
     *
     * @mbg.generated
     */
    private Integer correctChoice;

    /**
     * Database Column Remarks:
     *    ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_question_info.Word_Question_text
     *
     * @mbg.generated
     */
    private String wordQuestionText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_question_info.Word_Question_id
     *
     * @return the value of word_question_info.Word_Question_id
     *
     * @mbg.generated
     */
    public Integer getWordQuestionId() {
        return wordQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_question_info.Word_Question_id
     *
     * @param wordQuestionId the value for word_question_info.Word_Question_id
     *
     * @mbg.generated
     */
    public void setWordQuestionId(Integer wordQuestionId) {
        this.wordQuestionId = wordQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_question_info.Word_id
     *
     * @return the value of word_question_info.Word_id
     *
     * @mbg.generated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_question_info.Word_id
     *
     * @param wordId the value for word_question_info.Word_id
     *
     * @mbg.generated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_question_info.Correct_choice
     *
     * @return the value of word_question_info.Correct_choice
     *
     * @mbg.generated
     */
    public Integer getCorrectChoice() {
        return correctChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_question_info.Correct_choice
     *
     * @param correctChoice the value for word_question_info.Correct_choice
     *
     * @mbg.generated
     */
    public void setCorrectChoice(Integer correctChoice) {
        this.correctChoice = correctChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_question_info.Word_Question_text
     *
     * @return the value of word_question_info.Word_Question_text
     *
     * @mbg.generated
     */
    public String getWordQuestionText() {
        return wordQuestionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_question_info.Word_Question_text
     *
     * @param wordQuestionText the value for word_question_info.Word_Question_text
     *
     * @mbg.generated
     */
    public void setWordQuestionText(String wordQuestionText) {
        this.wordQuestionText = wordQuestionText == null ? null : wordQuestionText.trim();
    }
}