package com.eLearnPlayer.entity;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_to_collection_info
 */

public class WordToCollectionInfoKey {
    /**
     * Database Column Remarks:
     *   复合主键，收藏夹id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_to_collection_info.Word_Collection_id
     *
     * @mbg.generated
     */
    private Integer wordCollectionId;

    /**
     * Database Column Remarks:
     *   复合主键，单词id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_to_collection_info.Word_id
     *
     * @mbg.generated
     */
    private Integer wordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_to_collection_info.Word_Collection_id
     *
     * @return the value of word_to_collection_info.Word_Collection_id
     *
     * @mbg.generated
     */
    public Integer getWordCollectionId() {
        return wordCollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_to_collection_info.Word_Collection_id
     *
     * @param wordCollectionId the value for word_to_collection_info.Word_Collection_id
     *
     * @mbg.generated
     */
    public void setWordCollectionId(Integer wordCollectionId) {
        this.wordCollectionId = wordCollectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_to_collection_info.Word_id
     *
     * @return the value of word_to_collection_info.Word_id
     *
     * @mbg.generated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_to_collection_info.Word_id
     *
     * @param wordId the value for word_to_collection_info.Word_id
     *
     * @mbg.generated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }
}