package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_books_info
 */
@Table(name = "word_books_info")
public class WordBooksInfo {
    /**
     * Database Column Remarks:
     *   ������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_books_info.Book_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer bookId;

    /**
     * Database Column Remarks:
     *   ����������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_books_info.Book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     * Database Column Remarks:
     *   ���������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_books_info.Level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_books_info.Book_id
     *
     * @return the value of word_books_info.Book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_books_info.Book_id
     *
     * @param bookId the value for word_books_info.Book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_books_info.Book_name
     *
     * @return the value of word_books_info.Book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_books_info.Book_name
     *
     * @param bookName the value for word_books_info.Book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_books_info.Level
     *
     * @return the value of word_books_info.Level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_books_info.Level
     *
     * @param level the value for word_books_info.Level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}