package com.eLearnPlayer.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table word_choices_info
 */
@Table(name = "word_choices_info")
public class WordChoicesInfo {
    /**
     * Database Column Remarks:
     *   ѡ��id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_choices_info.Word_Choice_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer wordChoiceId;

    /**
     * Database Column Remarks:
     *   ���������id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_choices_info.Word_Question_id
     *
     * @mbg.generated
     */
    private Integer wordQuestionId;

    /**
     * Database Column Remarks:
     *    ѡ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_choices_info.Choice_index
     *
     * @mbg.generated
     */
    private Integer choiceIndex;

    /**
     * Database Column Remarks:
     *    ѡ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_choices_info.Choice_text
     *
     * @mbg.generated
     */
    private String choiceText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_choices_info.Word_Choice_id
     *
     * @return the value of word_choices_info.Word_Choice_id
     *
     * @mbg.generated
     */
    public Integer getWordChoiceId() {
        return wordChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_choices_info.Word_Choice_id
     *
     * @param wordChoiceId the value for word_choices_info.Word_Choice_id
     *
     * @mbg.generated
     */
    public void setWordChoiceId(Integer wordChoiceId) {
        this.wordChoiceId = wordChoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_choices_info.Word_Question_id
     *
     * @return the value of word_choices_info.Word_Question_id
     *
     * @mbg.generated
     */
    public Integer getWordQuestionId() {
        return wordQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_choices_info.Word_Question_id
     *
     * @param wordQuestionId the value for word_choices_info.Word_Question_id
     *
     * @mbg.generated
     */
    public void setWordQuestionId(Integer wordQuestionId) {
        this.wordQuestionId = wordQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_choices_info.Choice_index
     *
     * @return the value of word_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public Integer getChoiceIndex() {
        return choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_choices_info.Choice_index
     *
     * @param choiceIndex the value for word_choices_info.Choice_index
     *
     * @mbg.generated
     */
    public void setChoiceIndex(Integer choiceIndex) {
        this.choiceIndex = choiceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_choices_info.Choice_text
     *
     * @return the value of word_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public String getChoiceText() {
        return choiceText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_choices_info.Choice_text
     *
     * @param choiceText the value for word_choices_info.Choice_text
     *
     * @mbg.generated
     */
    public void setChoiceText(String choiceText) {
        this.choiceText = choiceText == null ? null : choiceText.trim();
    }
}